### ISSUE TITLE
HTTP_task type is set as SIMPLE

### ISSUE THREAD

**Issue by krishnaputhran** [FRINXio/frinx-workflow-ui#45]
When you see the json auto generated code for HTTP tasks, the type is set as "SIMPLE"

{
      "name": "HTTP_task",
      "taskReferenceName": "httpRequestTaskRef_VT7P",
      "inputParameters": {
        "http_request": {
          "uri": "${workflow.input.uri}",
          "method": "GET",
          "body": "",
          "contentType": "application/json",
          "headers": {},
          "timeout": "3600"
        }
      },
      "type": "SIMPLE",
      "startDelay": 0,
      "optional": false
    }

**Comment by marosmars** [comment]
Hey @krishnaputhran 

We have just recently changed this to SIMPLE, please see following commit https://github.com/FRINXio/frinx-workflow-ui/pull/41/files

Here's why:
- We have re-implemented the SYSTEM HTTP task as a python worker here: https://github.com/FRINXio/FRINX-machine/blob/master/microservices/netinfra_utils/workers/http_worker.py
- This python worker is : safer, more robust and exposes additional settings such as "verifyCertificates"
- Python HTTP worker preserves the API used by SYSTEM HTTP worker for compatibility
- We decided to switch the UI, so that it always uses SIMPLE task for HTTP mostly due to security reasons

**Comment by marosmars** [comment]
Note on security: 
- HTTP worker allows users to invoke any HTTP call
  - If you let conductor execute user requests that are outside of your control, users can easily use it for various exploits e.g. messing up with conductor
- The worker runs inside conductor server
  - Running arbitrary requests inside the server can negatively impact its operation
